<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYsdq1iA\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYsdq1iA/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYsdq1iA.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYsdq1iA\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYsdq1iA\App_KernelDevDebugContainer([
    'container.build_hash' => 'Ysdq1iA',
    'container.build_id' => 'dd5cf7d6',
    'container.build_time' => 1576233161,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYsdq1iA');
